Refactor Flask server starter scripts for efficiency and error handling

diff --git a/db-flask b/db-flask
--- a/db-flask
+++ b/db-flask
@@ -10,21 +10,42 @@ if [ "$#" -ne 1 ]; then
     exit 1
 fi
 
+# terminate the Flask server when the script exits
 kill_server() {
     echo -e "\nTerminating the server"
-    kill -9 "$(pgrep -laf "api.v1.app" | cut -f 1 -d ' ')" 2> /dev/null
+    pids=$(pgrep -laf "api.v1.app" | cut -f 1 -d ' ' | tr '\n' ' ')
+    for pid in $pids; do
+        kill -9 "$pid" 2> /dev/null
+    done
 }
 
 trap kill_server EXIT
 
 echo "Starting Flask Server"
 while true; do
-HBNB_MYSQL_USER=hbnb_dev HBNB_MYSQL_PWD=hbnb_dev_pwd \
-    HBNB_MYSQL_HOST=localhost HBNB_MYSQL_DB=hbnb_dev_db \
-    HBNB_TYPE_STORAGE=db HBNB_API_HOST=0.0.0.0 HBNB_API_PORT=5002 \
-    python3 -m api.v1.app 2> /dev/null &
+    if ! pgrep -laf "api.v1.app" > /dev/null; then
+        HBNB_MYSQL_USER=hbnb_dev HBNB_MYSQL_PWD=hbnb_dev_pwd \
+            HBNB_MYSQL_HOST=localhost HBNB_MYSQL_DB=hbnb_dev_db \
+            HBNB_TYPE_STORAGE=db HBNB_API_HOST=0.0.0.0 HBNB_API_PORT=5002 \
+            python3 -m api.v1.app 2> /dev/null &
+    fi
 
-    echo "Generating dummy data"
+    # let's wait for the server to start
+    sleep 3
+
+    # check if the server is running
+    if ! pgrep -laf "api.v1.app" > /dev/null; then
+        echo "Failed to start the server"
+        echo "Here are few things you can check:"
+        echo -e "\t1. Is the port 5002 already in use?"
+        echo -e "\t2. Is the database server running?"
+        echo -e "\t3. Is the database server accessible?"
+
+        exit 1
+    fi
+
+    # generate dummy data
+    echo -e "\nGenerating dummy data"
     HBNB_MYSQL_USER=hbnb_dev HBNB_MYSQL_PWD=hbnb_dev_pwd \
     HBNB_MYSQL_HOST=localhost HBNB_MYSQL_DB=hbnb_dev_db \
     HBNB_TYPE_STORAGE=db ./populate_storage.py "$1"
diff --git a/fs-flask b/fs-flask
--- a/fs-flask
+++ b/fs-flask
@@ -10,9 +10,13 @@ if [ "$#" -ne 1 ]; then
     exit 1
 fi
 
+# terminate the Flask server when the script exits
 kill_server() {
     echo -e "\nTerminating the server"
-    kill -9 "$(pgrep -laf "api.v1.app" | cut -f 1 -d ' ')" 2> /dev/null
+    pids=$(pgrep -laf "api.v1.app" | cut -f 1 -d ' ' | tr '\n' ' ')
+    for pid in $pids; do
+        kill -9 $pid 2> /dev/null
+    done
 }
 
 trap kill_server EXIT
@@ -20,6 +24,15 @@ trap kill_server EXIT
 echo "Starting Flask server"
 while true; do
     HBNB_API_PORT=5001 python3 -m api.v1.app 2> /dev/null &
+
+    # let's wait for the server to start
+    sleep 3
+
+    # check if the server is running
+    if ! pgrep -laf "api.v1.app" > /dev/null; then
+        echo "Failed to start the server"
+        exit 1
+    fi
 
     echo "Generating dummy data"
     python ./populate_storage.py "$1"
